version: '3'
services:
  proxy:
    links:
      - api
    ports:
      - 80:80
  api:
    links:
      - db
    environment:
      - PORT=80
      - MONGO_URL=mongodb://db:27017/todo
  db:
    image: mongo:3.4.6
