version: '3'
services:
  proxy:
    image: nginx:1.13-alpine
    links:
      - api
      - web
      - api-django
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  api:
    image: node:8.7-alpine
    links:
      - db
    environment:
      - PORT=80
      - MONGO_URL=mongodb://db:27017/todo
    volumes:
      - ./api:/opt/app
    entrypoint: /opt/app/entrypoint.sh
  api-django:
    image: python:3.6-alpine3.6
    volumes:
      - ./api-django:/opt/app
      - deps:/usr/local/lib/python3.6/site-packages
    entrypoint: /opt/app/entrypoint.sh
  web:
    image: node:8.7-alpine
    volumes:
      - ./web:/opt/app
    entrypoint: /opt/app/entrypoint.sh
  db:
    image: mongo:3.4
volumes:
  deps:
